version: '3'

services:
    frontend:
        build: ./frontend
        container_name: mudocker-front
        command: serve -s build -l 3000
        restart: unless-stopped
        stdin_open: true
        tty: true
        volumes:
            - ./frontend/src:/usr/src/app/src
        networks:
            - mudocker-network

    api:
        build: ./api
        container_name: mudocker-api
        command: npm run start
        restart: unless-stopped
        ports:
            - "3001:3001"
        environment:
            - PORT=3001
            - HOST=http://mudocker.com
            - MONGO_URL=mongodb://api_db:27017/api
            - AUTH_API_URL=http://auth:3002/api
        depends_on:
            - api_db
        networks:
            - mudocker-network

    auth:
        build: ./auth
        container_name: mudocker-auth
        command: npm run start
        restart: unless-stopped
        ports:
            - "3002:3002"
        environment:
            - PORT=3002
            - HOST=http://mudocker.com
            - MONGO_URL=mongodb://auth_db:27017/auth
            - API_URL=http://api:3001/api
        depends_on:
            - auth_db
        networks:
            - mudocker-network

    auth_db:
        image: mongo:latest
        container_name: mudocker-auth-db
        volumes:
            - mongodb_auth:/data/db
        logging:
            driver: none
        networks:
            - mudocker-network

    api_db:
        image: mongo:latest
        container_name: mudocker-api-db
        volumes:
            - mongodb_api:/data/db
        logging:
            driver: none
        networks:
            - mudocker-network

    nginx:
        image: nginx:stable-alpine
        container_name: mudocker-nginx
        ports:
            - "80:80"
        volumes:
            - ./nginx/nginx.conf.prod:/etc/nginx/conf.d/nginx.conf
        depends_on:
            - frontend
        networks:
            - mudocker-network

volumes:
    mongodb_api:
    mongodb_auth:

networks:
    mudocker-network:
        driver: bridge
